#import "@preview/acrostiche:0.5.1": *
#pagebreak()

= Example with Acronyms, Citations, Formulas, Tables and Images

#block(
  width: 100%,
  fill: rgb("#FFEEBA"),
  stroke: rgb("#FFD700"),
  radius: 4pt,
  inset: 10pt,
)[
  #align(center)[
    #text(weight: "bold")[IMPORTANT NOTE]
  ]
  
  This example was automatically generated by Claude 3.7 Sonnet (AI) and its accuracy has not been verified. It is provided only to show how the template works.
]

== Acronyms Usage

#acr("AI") has transformed numerous industries in recent years. The integration of #acr("ML") systems with #acr("NLP") capabilities has led to significant advances in automated text processing. For image recognition, #acr("CNN") architectures remain the preferred approach, while #acrpl("RNN") are typically used for sequential data analysis.

The plural form of acronyms can be used as shown with #acrpl("IoT"). These #acrpl("IoT") are becoming increasingly common in smart home applications.

If we need to display the full form again, we can reset the acronym: #reset-acronym("AI") and then use it again: #acr("AI").

== Citations Usage

According to @smith2023, there has been remarkable progress in developing intelligent systems. The application of machine learning to natural language processing has shown promising results @williams2022.

Multiple researchers @smith2023@williams2022@davis2021 have explored the connections between different AI subfields. Davis and Wilson's comprehensive guide @davis2021 provides an excellent foundation for understanding neural networks.

Recent security challenges in IoT implementations have been thoroughly analyzed @jones2024. This analysis is particularly important for understanding the vulnerabilities of interconnected systems.

== Mathematical Formulas

Mathematical expressions can be inserted inline like $E = m c^2$ or as block equations:

$ F(x) = integral_(- infinity)^(infinity) f(t) e^(-2 pi i t x) dif t $

For neural networks, the activation function ReLU is defined as:

$ "ReLU"(x) = max(0, x) $

The backpropagation algorithm uses the chain rule for computing gradients:

$ frac(partial L, partial w_(i j)) = frac(partial L, partial y_j) frac(partial y_j, partial w_(i j)) $

== Tables

Tables are useful for presenting structured data. Below is a comparison of different ML algorithms:

#figure(
  table(
    columns: (auto, auto, auto, auto),
    inset: 10pt,
    align: center,
    // Header row
    [*Algorithm*], [*Type*], [*Use Case*], [*Complexity*],
    // Data rows
    [Random Forest], [Ensemble], [Classification/Regression], [O($n log n$)],
    [SVM], [Kernel Methods], [Classification], [O($n^2$)],
    [K-Means], [Clustering], [Unsupervised Learning], [O($k times n times d$)],
    [LSTM], [Deep Learning], [Sequential Data], [O($n$)],
  ),
  caption: [Comparison of machine learning algorithms]
) <table-ml-algorithms>

As shown in @table-ml-algorithms, different algorithms are suitable for different tasks.

== Images

Images can be included from local files or URLs:

#figure(
  image("../img/network.png", width: 80%),
  caption: [Architecture diagram for a neural network]
) <fig-architecture>

@fig-architecture illustrates a typical neural network architecture used in modern #acr("AI") systems. Such architectures are extensively discussed in @davis2021.

== Combined Usage Example

#acr("ML") techniques described by @williams2022 can be integrated with #acr("IoT") systems to create smart environments. These environments present security challenges that were identified in @jones2024.

The mathematical model for a #acr("CNN") can be represented as:

$ h_i = sigma(sum_(j=1)^m w_(i j) dot x_j + b_i) $

Where $sigma$ is the activation function, as shown in the table @table-ml-algorithms.

The field of #acr("NLP") has seen significant advancements through the application of deep learning methods @davis2021. Several #acrpl("CNN") described in the literature @smith2023 have demonstrated superior performance in text classification tasks, as visualized in @fig-architecture.