// User variables
#let ai-title = "Acknowledgement of use of\nAI tools"
#let ai-content = [
  #text(weight: "bold")[Recognition of the use of generative Artificial Intelligence technologies and tools, software and other support tools.]
  
  #v(1em)
  
  I acknowledge the use of [insert AI system(s) and link] to [specific use of generative artificial intelligence or other tasks]. I acknowledge the use of [software, codes or platforms] to [specific use software, codes or platforms or to other tasks].
  
  #v(1em)
  
  #text(size: 9pt, style: "italic")[Example 1: I acknowledge the use of ChatGPT 3.5 (Open AI, https://chat.openai.com) to summarise the initial notes and to proofread the final draft and the use of Office365 (Microsoft, https://www.office.com) for text writing and productivity.]
  
  #v(1em)
  
  #text(size: 9pt, style: "italic")[Example 2: No content generated by AI technologies has been used in this Thesis.]
  
  #v(1em)
  
  #text(weight: "bold")[Note: You should add Claude 3.7 Sonnet since it was used as assistant in adapting the original Word template to this Typst version.]
]

// Main content
#block(
  width: 100%,
  height: 100%,
)[
  #set text(lang: "en")
  
  // First row - 5cm (empty rows)
  #place(
    top + left,
    block(
      width: 5.69cm,
      height: 5cm,
    )[]
  )
  
  #place(
    top + left,
    dx: 5.69cm,
    block(
      width: 12.43cm,
      height: 5cm,
    )[]
  )
  
  // Second row - 2.47cm (empty rows)
  #place(
    top + left,
    dy: 5cm,
    block(
      width: 5.69cm,
      height: 2.47cm,
    )[]
  )
  
  #place(
    top + left,
    dx: 5.69cm,
    dy: 5cm,
    block(
      width: 12.43cm,
      height: 2.47cm,
    )[]
  )
  
  // Third row - 16.23cm (AI acknowledgement)
  #place(
    top + left,
    dy: 7.47cm,
    block(
      width: 5.69cm,
      height: 16.23cm,
    )[
      #pad(top: -8pt)[
        #align(left)[
          #set text(size: 11pt, weight: "bold")
          #ai-title
        ]
      ]
    ]
  )
  
  #place(
    top + left,
    dx: 5.69cm,
    dy: 7.47cm,
    block(
      width: 12.43cm,
      height: 16.23cm,
    )[
      #pad(top: -8pt)[
        #align(left)[
          #ai-content
        ]
      ]
    ]
  )
]